namespace ThreadCraft.Web.Components.Viz.Explainers;

public static partial class SceneLibrary
{
    private static ExplainerScene RaceInterleaving() => new(
        "race-interleaving", "Under the hood: same code, two outcomes", 760, 380,
        Nodes:
        [
            new("la",  30,  30, 230, 315, "Thread A", null, SceneNodeShape.Lane),
            new("a1",  50,  60, 190, 48, "① read counter"),
            new("a2",  50, 130, 190, 48, "② add 1"),
            new("a3",  50, 200, 190, 48, "③ write counter"),
            new("ar",  50, 275, 190, 44, "A's copy", "= —"),
            new("lb", 500,  30, 230, 315, "Thread B", null, SceneNodeShape.Lane),
            new("b1", 520,  60, 190, 48, "① read counter"),
            new("b2", 520, 130, 190, 48, "② add 1"),
            new("b3", 520, 200, 190, 48, "③ write counter"),
            new("br", 520, 275, 190, 44, "B's copy", "= —"),
            new("counter", 310, 140, 140, 64, "counter", "= 0", SceneNodeShape.Round),
            new("result",  295, 275, 170, 56, "Outcome", "unknown", SceneNodeShape.Pill),
        ],
        Edges:
        [
            new("e-a1", 240,  84, 330, 160, null, Dashed: true),
            new("e-a3", 240, 224, 330, 190, null, Dashed: true),
            new("e-b1", 520,  84, 430, 160, null, Dashed: true),
            new("e-b3", 520, 224, 430, 190, null, Dashed: true),
        ],
        Tokens: [ new("slice", "CPU ⚡", "counter", Dy: 44, Hidden: true) ],
        Steps:
        [
            new() { Title = "Two threads, one counter",
                Narration = "Both threads must do read → add → write. Three tiny steps each. Looks completely innocent.",
                Active = ["la", "lb", "counter"] },
            new() { Title = "Lucky timing: A reads first",
                Narration = "The CPU runs A: it reads counter = 0 into its own copy.",
                Show = ["slice"], Moves = new() { ["slice"] = new("a1", Dx: 55, Dy: 15) },
                Subs = new() { ["ar"] = "= 0" },
                Flow = ["e-a1"], Active = ["a1", "counter"] },
            new() { Title = "A adds 1 and writes it back",
                Narration = "Still A: 0 + 1 = 1, written back to the shared counter. No interruption — safe.",
                Moves = new() { ["slice"] = new("a3", Dx: 55, Dy: 15) },
                Subs = new() { ["counter"] = "= 1" },
                Flow = ["e-a3"], Active = ["a3", "counter"] },
            new() { Title = "Then B does the same",
                Narration = "B reads 1, adds 1, writes 2. Two increments, counter = 2. Correct!",
                Moves = new() { ["slice"] = new("b3", Dx: -55, Dy: 15) },
                Subs = new() { ["br"] = "= 1", ["counter"] = "= 2", ["result"] = "2 ✓ correct" },
                Flow = ["e-b3"], Active = ["b3", "result"] },
            new() { Title = "But the scheduler can switch ANYWHERE",
                Narration = "Rewind. The OS may move the CPU mid-operation — between ANY two instructions. Watch the dice land differently…",
                Moves = new() { ["slice"] = new("counter", Dy: 44) },
                Subs = new() { ["counter"] = "= 0", ["ar"] = "= —", ["br"] = "= —", ["result"] = "unknown" },
                Active = ["counter"] },
            new() { Title = "A reads 0 — then gets FROZEN",
                Narration = "A reads counter = 0 into its copy… and the scheduler yanks the CPU away at exactly this moment.",
                Moves = new() { ["slice"] = new("a1", Dx: 55, Dy: 15) },
                Subs = new() { ["ar"] = "= 0" },
                Flow = ["e-a1"], Active = ["a1"], Dimmed = ["lb"] },
            new() { Title = "B reads — still 0!",
                Narration = "Now B reads the counter. A has not written yet, so B ALSO sees 0. Both copies say 0.",
                Moves = new() { ["slice"] = new("b1", Dx: -55, Dy: 15) },
                Subs = new() { ["br"] = "= 0" },
                Flow = ["e-b1"], Active = ["b1", "counter"] },
            new() { Title = "A writes 1…",
                Narration = "A wakes up, adds 1 to ITS copy (0 + 1) and writes 1. It has no idea B also read.",
                Moves = new() { ["slice"] = new("a3", Dx: 55, Dy: 15) },
                Subs = new() { ["counter"] = "= 1" },
                Flow = ["e-a3"], Active = ["a3", "counter"] },
            new() { Title = "…B also writes 1",
                Narration = "B adds 1 to ITS copy (also 0 + 1) and writes 1 — overwriting A's result. Two increments ran; only one survived.",
                Moves = new() { ["slice"] = new("b3", Dx: -55, Dy: 15) },
                Subs = new() { ["counter"] = "= 1", ["result"] = "1 ✗ LOST UPDATE" },
                Flow = ["e-b3"], Active = ["b3", "result"] },
            new() { Title = "Same code, different dice",
                Narration = "The bug appears ONLY if the switch lands mid-operation. That is why it hides 49 runs out of 50 — and why looping the code 100 times forces it into the open.",
                Active = ["result"] },
        ]);
}
